require('jpv.colorscheme')
require('jpv.telescope')
require('jpv.options')
require('jpv.keymaps')
require('jpv.completion')
--require('jpv.installer')
-- require('jpv.lspconfig')
--require('jpv.coq')
require('jpv.lsp')
--require('jpv.dap')
--require('jpv.lspsaga')
--require('jpv.mason')
--require('jpv.toggleterm')
--require('jpv.treesitter')
require('jpv.coc')
