require('jpv.autopairs')
require('jpv.telescope')
require('jpv.lsp')
require('jpv.nvim-cmp')
require('jpv.nvimtree')
require('jpv.options')
require('jpv.keymaps')
require('jpv.toggleterm')
-- require('jpv.coc')
require('jpv.lualine')
