require("jpv.autopairs")
require("jpv.telescope")
require("jpv.dap") -- require('jpv.coc')
require("jpv.nvim-cmp")
require("jpv.lsp")
require("jpv.nvimtree")
require("jpv.options")
require("jpv.keymaps")
require("jpv.toggleterm")
require("jpv.treesitter")
require("jpv.lualine")
require("jpv.gitsigns")
require("jpv.project")
